### ISSUE TITLE
Request for Item Descriptions

### ISSUE THREAD

**Issue by YiyanXu** [westlake-repl/PixelRec#1]
Hi, it appears that the "item information" currently only includes semantic details such as the item title and tags, but lacks any description about the item. Are the item descriptions available?

**Comment by hyc9** [comment]
Yes, we will make them public as soon as possible. Once we have these updates in place, we will inform you here, hope that helps.

**Comment by hyc9** [comment]
> Hi, it appears that the "item information" currently only includes semantic details such as the item title and tags, but lacks any description about the item. Are the item descriptions available?

Hello, we have updated the description about the item, you can download them via links now.
